// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RemSlyApi.Datas;

#nullable disable

namespace RemSlyApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231031105013_ReservationSession")]
    partial class ReservationSession
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClubMaterial", b =>
                {
                    b.Property<int>("ClubsId")
                        .HasColumnType("int");

                    b.Property<int>("MaterialsId")
                        .HasColumnType("int");

                    b.HasKey("ClubsId", "MaterialsId");

                    b.HasIndex("MaterialsId");

                    b.ToTable("ClubMaterial");
                });

            modelBuilder.Entity("RemSlyCore.Models.Club", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Is24h")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLadiesOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OpeningHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Clubs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "43 Bd de Valmy, 59650 Villeneuve-d'Ascq",
                            Description = "Bienvenu chez Sunstar! Nous disposons d'une large gamme d'appareils de fitness et de cours collectifs. Passez nous voir au club pour choisir l'activité sportive qui vous convient le mieux.",
                            Email = "Sunstar@club.com",
                            ImageUrl = "/Images/Club/Abbeville.jpg",
                            Is24h = false,
                            IsLadiesOnly = false,
                            Name = "Sunstar Club",
                            OpeningHours = "10h00 - 20h00",
                            PhoneNumber = "0366333344",
                            PostalCode = "59650"
                        },
                        new
                        {
                            Id = 2,
                            Address = "292 Rue des Fusillés, 59493 Villeneuve-d'Ascq",
                            Description = "Bienvenu chez Cortex! Notre club est équipé d'une large gamme d'appareils de fitness et propose de nombreux cours collectifs.",
                            Email = "Cortex@club.com",
                            ImageUrl = "/Images/Club/Argentan.webp",
                            Is24h = false,
                            IsLadiesOnly = false,
                            Name = "Cortex Club",
                            OpeningHours = "09h00 - 21h00",
                            PhoneNumber = "0320597941",
                            PostalCode = "59493"
                        },
                        new
                        {
                            Id = 3,
                            Address = "5 Pl. Pierre de Coubertin, 59790 Ronchin",
                            Description = "Bienvenu chez Cabana ! Adonnez-vous à votre activité sportive favorite chez Cabana Ladies et retrouvez la forme, sur nos appareils de fitness ou en suivant des cours collectifs.",
                            Email = "zumba@hotmail.com",
                            ImageUrl = "/Images/Club/Belgique.jpg",
                            Is24h = false,
                            IsLadiesOnly = true,
                            Name = "Cabana Club",
                            OpeningHours = "08h00 - 22h00",
                            PhoneNumber = "0359613012",
                            PostalCode = "59790"
                        },
                        new
                        {
                            Id = 4,
                            Address = "124 Rue de Douai, 59000 Lille",
                            Description = "Bienvenu chez Kinetic ! Notre club est équipé d'une large gamme d'appareils de fitness et propose de nombreux cours collectifs.",
                            Email = "Kinetic@outlook.com",
                            ImageUrl = "/Images/Club/Bessines.jpg",
                            Is24h = false,
                            IsLadiesOnly = false,
                            Name = "Kinetic Club",
                            OpeningHours = "09h30 - 21h00",
                            PhoneNumber = "0320597941",
                            PostalCode = "59000"
                        },
                        new
                        {
                            Id = 5,
                            Address = "20 Rue des Meuniers, 59810 Lesquin",
                            Description = "Bienvenu chez Optimum 24/7 ! Besoin de vous entrainer à toute heure, nous disposons de la solution d'entraînement qui répond à vos besoins : Notre club vous accueille 24h/24h !",
                            Email = "Optimum@yahoo.com",
                            ImageUrl = "/Images/Club/Bruay.jpg",
                            Is24h = true,
                            IsLadiesOnly = false,
                            Name = "Optimum Club",
                            OpeningHours = "00h00 - 24h00",
                            PhoneNumber = "0771630955",
                            PostalCode = "59810"
                        },
                        new
                        {
                            Id = 6,
                            Address = "202 Rue Solférino, 59000 Lille",
                            Description = "Bienvenu chez Magellan ! Notre club est équipé d'une large gamme d'appareils de fitness et propose de nombreux cours collectifs.",
                            Email = "Magellan@gmail.com",
                            ImageUrl = "/Images/Club/Cambrai.jpg",
                            Is24h = false,
                            IsLadiesOnly = false,
                            Name = "Magellan Club",
                            OpeningHours = "06h00 - 23h00",
                            PhoneNumber = "0967583899",
                            PostalCode = "59000"
                        },
                        new
                        {
                            Id = 7,
                            Address = "4 Rue Professeur Langevin, 59000 Lille",
                            Description = "Bienvenu chez Pixel ! Nous disposons d'une large gamme d'appareils de fitness et de cours collectifs. Passez nous voir au club pour choisir l'activité sportive qui vous convient le mieux.",
                            Email = "Pixel@gmail.com",
                            ImageUrl = "/Images/Club/Courcelles.jpg",
                            Is24h = false,
                            IsLadiesOnly = false,
                            Name = "Pixel Club",
                            OpeningHours = "07h00 - 22h00",
                            PhoneNumber = "0320309838",
                            PostalCode = "59000"
                        },
                        new
                        {
                            Id = 8,
                            Address = "3 bis Rue Edouard Delesalle, 59000 Lille",
                            Description = "Bienvenu chez Axion ! Quels que soient votre âge, votre niveau de pratique ou l'heure, nous serons à vos côtés pour répondre à vos besoins spécifiques.",
                            Email = "Axion@gmail.com",
                            ImageUrl = "/Images/Club/Dax.jpg",
                            Is24h = true,
                            IsLadiesOnly = false,
                            Name = "Axion Club",
                            OpeningHours = "06h00 - 23h00",
                            PhoneNumber = "0320550808",
                            PostalCode = "59000"
                        },
                        new
                        {
                            Id = 9,
                            Address = "124 Rue de Douai, 59000 Lille",
                            Description = "Bienvenu chez Panda ! Notre club dédié au femme est là pour vous accompagner dans votre remise en forme en proposant de nombreux cours collectifs.",
                            Email = "Panda@gmail.com",
                            ImageUrl = "/Images/Club/Jodoigne.jpeg",
                            Is24h = false,
                            IsLadiesOnly = true,
                            Name = "Panda Club",
                            OpeningHours = "09h30 - 21h00",
                            PhoneNumber = "0320597941",
                            PostalCode = "59000"
                        },
                        new
                        {
                            Id = 10,
                            Address = "124 Rue de Douai, 59000 Lille",
                            Description = "Bienvenu chez Vita ! Notre club vous accompagnes 24h/24 tous les jours de la semaine, dans vos besoins sportifs pour être plein de vitalité !",
                            Email = "Vita@gmail.com",
                            ImageUrl = "/Images/Club/Pau.jpg",
                            Is24h = true,
                            IsLadiesOnly = false,
                            Name = "Vita Club",
                            OpeningHours = "00h00 - 24h00",
                            PhoneNumber = "0320597941",
                            PostalCode = "59000"
                        },
                        new
                        {
                            Id = 11,
                            Address = "62 Rue d'Iéna, 59000 Lille",
                            Description = "Bienvenu chez Luminous Club ! Venez découvrir le sport autrement dans notre salle sur les toits de la ville",
                            Email = "Luminous@gmail.com",
                            ImageUrl = "/Images/Club/Vesoul.jpg",
                            Is24h = false,
                            IsLadiesOnly = false,
                            Name = "Luminous Club",
                            OpeningHours = "10h00 - 17h00",
                            PhoneNumber = "0362859280",
                            PostalCode = "59000"
                        });
                });

            modelBuilder.Entity("RemSlyCore.Models.Commentary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("UserId");

                    b.ToTable("Commentaries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Super séance, le coach ambiance la séance et motive bien l'ensemble des participants.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 852, DateTimeKind.Local).AddTicks(9761),
                            SessionId = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Content = "J'ai adoré participé à ce cours collectifs.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(7985),
                            SessionId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Content = "Top! Hyper intense.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8005),
                            SessionId = 2,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            Content = "Le cours est énergisant",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8009),
                            SessionId = 2,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Content = "Ambiance conviviale. Je ne regrette pas mon choix, c’est top!!",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8010),
                            SessionId = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 6,
                            Content = "L'équipe est toujours présente pour nous aider si besoin.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8015),
                            SessionId = 3,
                            UserId = 5
                        },
                        new
                        {
                            Id = 7,
                            Content = "Super séance, le coach ambiance la séance et motive bien l'ensemble des participants.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8017),
                            SessionId = 4,
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            Content = "J'ai adoré participé à ce cours collectifs.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8019),
                            SessionId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            Content = "Top! Hyper intense.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8021),
                            SessionId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            Content = "Ambiance conviviale. Je ne regrette pas mon choix, c’est top!!",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8023),
                            SessionId = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 11,
                            Content = "Top! Hyper pédagogue et super séance.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8025),
                            SessionId = 6,
                            UserId = 3
                        },
                        new
                        {
                            Id = 12,
                            Content = "Le cours est très complet",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8027),
                            SessionId = 6,
                            UserId = 5
                        },
                        new
                        {
                            Id = 13,
                            Content = "Super séance, le coach ambiance la séance et motive bien l'ensemble des participants.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8029),
                            SessionId = 7,
                            UserId = 1
                        },
                        new
                        {
                            Id = 14,
                            Content = "J'ai adoré participé à ce cours collectifs.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8030),
                            SessionId = 7,
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            Content = "Ambiance conviviale. Je ne regrette pas mon choix, c’est top!!",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8032),
                            SessionId = 8,
                            UserId = 1
                        },
                        new
                        {
                            Id = 16,
                            Content = "L'équipe est toujours présente pour nous aider si besoin.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8034),
                            SessionId = 8,
                            UserId = 4
                        },
                        new
                        {
                            Id = 17,
                            Content = "Top! Hyper pédagogue et super séance.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8036),
                            SessionId = 9,
                            UserId = 3
                        },
                        new
                        {
                            Id = 18,
                            Content = "Le cours est très complet",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8038),
                            SessionId = 9,
                            UserId = 5
                        },
                        new
                        {
                            Id = 19,
                            Content = "Super séance, le coach ambiance la séance et motive bien l'ensemble des participants.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8041),
                            SessionId = 10,
                            UserId = 1
                        },
                        new
                        {
                            Id = 20,
                            Content = "Ambiance conviviale. Je ne regrette pas mon choix, c’est top!!",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8043),
                            SessionId = 10,
                            UserId = 2
                        },
                        new
                        {
                            Id = 21,
                            Content = "Top! Hyper intense.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8044),
                            SessionId = 11,
                            UserId = 2
                        },
                        new
                        {
                            Id = 22,
                            Content = "Le cours est énergisant",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8046),
                            SessionId = 11,
                            UserId = 4
                        },
                        new
                        {
                            Id = 23,
                            Content = "Top! Hyper pédagogue et super séance.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8048),
                            SessionId = 12,
                            UserId = 3
                        },
                        new
                        {
                            Id = 24,
                            Content = "Le cours est très complet",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8050),
                            SessionId = 12,
                            UserId = 5
                        },
                        new
                        {
                            Id = 25,
                            Content = "Ambiance conviviale. Je ne regrette pas mon choix, c’est top!!",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8051),
                            SessionId = 13,
                            UserId = 1
                        },
                        new
                        {
                            Id = 26,
                            Content = "L'équipe est toujours présente pour nous aider si besoin.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8053),
                            SessionId = 13,
                            UserId = 5
                        },
                        new
                        {
                            Id = 27,
                            Content = "Super séance, le coach ambiance la séance et motive bien l'ensemble des participants.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8055),
                            SessionId = 14,
                            UserId = 1
                        },
                        new
                        {
                            Id = 28,
                            Content = "J'ai adoré participé à ce cours collectifs.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8056),
                            SessionId = 14,
                            UserId = 2
                        },
                        new
                        {
                            Id = 29,
                            Content = "Top! Hyper intense.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8058),
                            SessionId = 15,
                            UserId = 2
                        },
                        new
                        {
                            Id = 30,
                            Content = "Ambiance conviviale. Je ne regrette pas mon choix, c’est top!!",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8060),
                            SessionId = 15,
                            UserId = 4
                        },
                        new
                        {
                            Id = 31,
                            Content = "Top! Hyper pédagogue et super séance.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8062),
                            SessionId = 16,
                            UserId = 3
                        },
                        new
                        {
                            Id = 32,
                            Content = "Le cours est très complet",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8063),
                            SessionId = 16,
                            UserId = 5
                        },
                        new
                        {
                            Id = 33,
                            Content = "Super séance, le coach ambiance la séance et motive bien l'ensemble des participants.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8065),
                            SessionId = 17,
                            UserId = 1
                        },
                        new
                        {
                            Id = 34,
                            Content = "J'ai adoré participé à ce cours collectifs.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8068),
                            SessionId = 17,
                            UserId = 2
                        },
                        new
                        {
                            Id = 35,
                            Content = "Ambiance conviviale. Je ne regrette pas mon choix, c’est top!!",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8070),
                            SessionId = 18,
                            UserId = 1
                        },
                        new
                        {
                            Id = 36,
                            Content = "L'équipe est toujours présente pour nous aider si besoin.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8071),
                            SessionId = 18,
                            UserId = 4
                        },
                        new
                        {
                            Id = 37,
                            Content = "Top! Hyper pédagogue et super séance.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8073),
                            SessionId = 19,
                            UserId = 3
                        },
                        new
                        {
                            Id = 38,
                            Content = "Le cours est très complet",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8075),
                            SessionId = 19,
                            UserId = 5
                        },
                        new
                        {
                            Id = 39,
                            Content = "Super séance, le coach ambiance la séance et motive bien l'ensemble des participants.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8131),
                            SessionId = 20,
                            UserId = 1
                        },
                        new
                        {
                            Id = 40,
                            Content = "Ambiance conviviale. Je ne regrette pas mon choix, c’est top!!",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8134),
                            SessionId = 20,
                            UserId = 2
                        },
                        new
                        {
                            Id = 41,
                            Content = "Top! Hyper intense.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8136),
                            SessionId = 21,
                            UserId = 2
                        },
                        new
                        {
                            Id = 42,
                            Content = "Le cours est énergisant",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8137),
                            SessionId = 21,
                            UserId = 4
                        },
                        new
                        {
                            Id = 43,
                            Content = "Top! Hyper pédagogue et super séance.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8139),
                            SessionId = 22,
                            UserId = 3
                        },
                        new
                        {
                            Id = 44,
                            Content = "Le cours est très complet",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8141),
                            SessionId = 22,
                            UserId = 5
                        },
                        new
                        {
                            Id = 45,
                            Content = "Ambiance conviviale. Je ne regrette pas mon choix, c’est top!!",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8143),
                            SessionId = 23,
                            UserId = 1
                        },
                        new
                        {
                            Id = 46,
                            Content = "L'équipe est toujours présente pour nous aider si besoin.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8144),
                            SessionId = 23,
                            UserId = 5
                        },
                        new
                        {
                            Id = 47,
                            Content = "Super séance, le coach ambiance la séance et motive bien l'ensemble des participants.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8146),
                            SessionId = 24,
                            UserId = 1
                        },
                        new
                        {
                            Id = 48,
                            Content = "J'ai adoré participé à ce cours collectifs.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8148),
                            SessionId = 24,
                            UserId = 2
                        },
                        new
                        {
                            Id = 49,
                            Content = "Top! Hyper intense.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8150),
                            SessionId = 25,
                            UserId = 2
                        },
                        new
                        {
                            Id = 50,
                            Content = "Ambiance conviviale. Je ne regrette pas mon choix, c’est top!!",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8151),
                            SessionId = 25,
                            UserId = 4
                        },
                        new
                        {
                            Id = 51,
                            Content = "Top! Hyper pédagogue et super séance.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8153),
                            SessionId = 26,
                            UserId = 3
                        },
                        new
                        {
                            Id = 52,
                            Content = "Le cours est très complet",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8155),
                            SessionId = 26,
                            UserId = 5
                        },
                        new
                        {
                            Id = 53,
                            Content = "Super séance, le coach ambiance la séance et motive bien l'ensemble des participants.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8156),
                            SessionId = 27,
                            UserId = 1
                        },
                        new
                        {
                            Id = 54,
                            Content = "J'ai adoré participé à ce cours collectifs.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8158),
                            SessionId = 27,
                            UserId = 2
                        },
                        new
                        {
                            Id = 55,
                            Content = "Ambiance conviviale. Je ne regrette pas mon choix, c’est top!!",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8160),
                            SessionId = 28,
                            UserId = 1
                        },
                        new
                        {
                            Id = 56,
                            Content = "L'équipe est toujours présente pour nous aider si besoin.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8161),
                            SessionId = 28,
                            UserId = 4
                        },
                        new
                        {
                            Id = 57,
                            Content = "Top! Hyper pédagogue et super séance.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8163),
                            SessionId = 29,
                            UserId = 3
                        },
                        new
                        {
                            Id = 58,
                            Content = "Le cours est très complet",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8165),
                            SessionId = 29,
                            UserId = 5
                        },
                        new
                        {
                            Id = 59,
                            Content = "Super séance, le coach ambiance la séance et motive bien l'ensemble des participants.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8167),
                            SessionId = 30,
                            UserId = 1
                        },
                        new
                        {
                            Id = 60,
                            Content = "Ambiance conviviale. Je ne regrette pas mon choix, c’est top!!",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8168),
                            SessionId = 30,
                            UserId = 2
                        },
                        new
                        {
                            Id = 61,
                            Content = "Top! Hyper intense.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8170),
                            SessionId = 31,
                            UserId = 2
                        },
                        new
                        {
                            Id = 62,
                            Content = "Le cours est énergisant",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8172),
                            SessionId = 31,
                            UserId = 4
                        },
                        new
                        {
                            Id = 63,
                            Content = "Top! Hyper pédagogue et super séance.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8174),
                            SessionId = 32,
                            UserId = 3
                        },
                        new
                        {
                            Id = 64,
                            Content = "Le cours est très complet",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8175),
                            SessionId = 32,
                            UserId = 5
                        },
                        new
                        {
                            Id = 65,
                            Content = "Ambiance conviviale. Je ne regrette pas mon choix, c’est top!!",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8177),
                            SessionId = 33,
                            UserId = 1
                        },
                        new
                        {
                            Id = 66,
                            Content = "L'équipe est toujours présente pour nous aider si besoin.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8181),
                            SessionId = 33,
                            UserId = 5
                        },
                        new
                        {
                            Id = 67,
                            Content = "Super séance, le coach ambiance la séance et motive bien l'ensemble des participants.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8182),
                            SessionId = 7,
                            UserId = 1
                        },
                        new
                        {
                            Id = 68,
                            Content = "J'ai adoré participé à ce cours collectifs.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8184),
                            SessionId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 69,
                            Content = "Top! Hyper intense.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8186),
                            SessionId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 70,
                            Content = "Ambiance conviviale. Je ne regrette pas mon choix, c’est top!!",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8187),
                            SessionId = 5,
                            UserId = 4
                        },
                        new
                        {
                            Id = 71,
                            Content = "Top! Hyper pédagogue et super séance.",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8189),
                            SessionId = 1,
                            UserId = 3
                        },
                        new
                        {
                            Id = 72,
                            Content = "Le cours est très complet",
                            Created = new DateTime(2023, 10, 31, 11, 50, 12, 855, DateTimeKind.Local).AddTicks(8191),
                            SessionId = 3,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("RemSlyCore.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("RemSlyCore.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Reservation");
                });

            modelBuilder.Entity("RemSlyCore.Models.ReservationSession", b =>
                {
                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.HasKey("SessionId", "ReservationId");

                    b.HasIndex("ReservationId");

                    b.ToTable("ReservationSessions");
                });

            modelBuilder.Entity("RemSlyCore.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CapacityMax")
                        .HasColumnType("int");

                    b.Property<int>("ClubId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsComplete")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Schedules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClubId");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CapacityMax = 10,
                            ClubId = 1,
                            ImageUrl = "/Images/Session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Live",
                            Schedules = "10h00",
                            Score = 4
                        },
                        new
                        {
                            Id = 2,
                            CapacityMax = 20,
                            ClubId = 1,
                            ImageUrl = "/Images/Session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Virtuel",
                            Schedules = "15h00",
                            Score = 3
                        },
                        new
                        {
                            Id = 3,
                            CapacityMax = 2,
                            ClubId = 1,
                            ImageUrl = "/Images/Session/PersonalTrainer.jpeg",
                            IsComplete = false,
                            Name = "Entraineur Personnel",
                            Schedules = "18h00",
                            Score = 5
                        },
                        new
                        {
                            Id = 4,
                            CapacityMax = 10,
                            ClubId = 2,
                            ImageUrl = "/images/session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Live",
                            Schedules = "10h00",
                            Score = 4
                        },
                        new
                        {
                            Id = 5,
                            CapacityMax = 20,
                            ClubId = 2,
                            ImageUrl = "/images/session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Virtuel",
                            Schedules = "15h00",
                            Score = 3
                        },
                        new
                        {
                            Id = 6,
                            CapacityMax = 2,
                            ClubId = 2,
                            ImageUrl = "/images/session/PersonalTrainer.jpeg",
                            IsComplete = false,
                            Name = "Entraineur Personnel",
                            Schedules = "18h00",
                            Score = 5
                        },
                        new
                        {
                            Id = 7,
                            CapacityMax = 10,
                            ClubId = 3,
                            ImageUrl = "/Images/Session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Live",
                            Schedules = "10h00",
                            Score = 4
                        },
                        new
                        {
                            Id = 8,
                            CapacityMax = 20,
                            ClubId = 3,
                            ImageUrl = "/Images/Session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Virtuel",
                            Schedules = "15h00",
                            Score = 3
                        },
                        new
                        {
                            Id = 9,
                            CapacityMax = 2,
                            ClubId = 3,
                            ImageUrl = "/Images/Session/PersonalTrainer.jpeg",
                            IsComplete = false,
                            Name = "Entraineur Personnel",
                            Schedules = "18h00",
                            Score = 5
                        },
                        new
                        {
                            Id = 10,
                            CapacityMax = 10,
                            ClubId = 4,
                            ImageUrl = "/images/session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Live",
                            Schedules = "10h00",
                            Score = 4
                        },
                        new
                        {
                            Id = 11,
                            CapacityMax = 20,
                            ClubId = 4,
                            ImageUrl = "/images/session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Virtuel",
                            Schedules = "15h00",
                            Score = 3
                        },
                        new
                        {
                            Id = 12,
                            CapacityMax = 2,
                            ClubId = 4,
                            ImageUrl = "/images/session/PersonalTrainer.jpeg",
                            IsComplete = false,
                            Name = "Entraineur Personnel",
                            Schedules = "18h00",
                            Score = 5
                        },
                        new
                        {
                            Id = 13,
                            CapacityMax = 10,
                            ClubId = 5,
                            ImageUrl = "/images/session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Live",
                            Schedules = "10h00",
                            Score = 4
                        },
                        new
                        {
                            Id = 14,
                            CapacityMax = 20,
                            ClubId = 5,
                            ImageUrl = "/images/session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Virtuel",
                            Schedules = "15h00",
                            Score = 3
                        },
                        new
                        {
                            Id = 15,
                            CapacityMax = 2,
                            ClubId = 5,
                            ImageUrl = "/images/session/PersonalTrainer.jpeg",
                            IsComplete = false,
                            Name = "Entraineur Personnel",
                            Schedules = "18h00",
                            Score = 5
                        },
                        new
                        {
                            Id = 16,
                            CapacityMax = 10,
                            ClubId = 6,
                            ImageUrl = "/images/session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Live",
                            Schedules = "10h00",
                            Score = 4
                        },
                        new
                        {
                            Id = 17,
                            CapacityMax = 20,
                            ClubId = 6,
                            ImageUrl = "/images/session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Virtuel",
                            Schedules = "15h00",
                            Score = 3
                        },
                        new
                        {
                            Id = 18,
                            CapacityMax = 2,
                            ClubId = 6,
                            ImageUrl = "/images/session/PersonalTrainer.jpeg",
                            IsComplete = false,
                            Name = "Entraineur Personnel",
                            Schedules = "18h00",
                            Score = 5
                        },
                        new
                        {
                            Id = 19,
                            CapacityMax = 10,
                            ClubId = 7,
                            ImageUrl = "/images/session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Live",
                            Schedules = "10h00",
                            Score = 4
                        },
                        new
                        {
                            Id = 20,
                            CapacityMax = 20,
                            ClubId = 7,
                            ImageUrl = "/images/session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Virtuel",
                            Schedules = "15h00",
                            Score = 3
                        },
                        new
                        {
                            Id = 21,
                            CapacityMax = 2,
                            ClubId = 7,
                            ImageUrl = "/images/session/PersonalTrainer.jpeg",
                            IsComplete = false,
                            Name = "Entraineur Personnel",
                            Schedules = "18h00",
                            Score = 5
                        },
                        new
                        {
                            Id = 22,
                            CapacityMax = 10,
                            ClubId = 8,
                            ImageUrl = "/Images/Session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Live",
                            Schedules = "10h00",
                            Score = 4
                        },
                        new
                        {
                            Id = 23,
                            CapacityMax = 20,
                            ClubId = 8,
                            ImageUrl = "/Images/Session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Virtuel",
                            Schedules = "15h00",
                            Score = 3
                        },
                        new
                        {
                            Id = 24,
                            CapacityMax = 2,
                            ClubId = 8,
                            ImageUrl = "/Images/Session/PersonalTrainer.jpeg",
                            IsComplete = false,
                            Name = "Entraineur Personnel",
                            Schedules = "18h00",
                            Score = 5
                        },
                        new
                        {
                            Id = 25,
                            CapacityMax = 10,
                            ClubId = 9,
                            ImageUrl = "/images/session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Live",
                            Schedules = "10h00",
                            Score = 4
                        },
                        new
                        {
                            Id = 26,
                            CapacityMax = 20,
                            ClubId = 9,
                            ImageUrl = "/images/session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Virtuel",
                            Schedules = "15h00",
                            Score = 3
                        },
                        new
                        {
                            Id = 27,
                            CapacityMax = 2,
                            ClubId = 9,
                            ImageUrl = "/images/session/PersonalTrainer.jpeg",
                            IsComplete = false,
                            Name = "Entraineur Personnel",
                            Schedules = "18h00",
                            Score = 5
                        },
                        new
                        {
                            Id = 28,
                            CapacityMax = 10,
                            ClubId = 10,
                            ImageUrl = "/images/session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Live",
                            Schedules = "10h00",
                            Score = 4
                        },
                        new
                        {
                            Id = 29,
                            CapacityMax = 20,
                            ClubId = 10,
                            ImageUrl = "/images/session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Virtuel",
                            Schedules = "15h00",
                            Score = 3
                        },
                        new
                        {
                            Id = 30,
                            CapacityMax = 2,
                            ClubId = 10,
                            ImageUrl = "/images/session/PersonalTrainer.jpeg",
                            IsComplete = false,
                            Name = "Entraineur Personnel",
                            Schedules = "18h00",
                            Score = 5
                        },
                        new
                        {
                            Id = 31,
                            CapacityMax = 10,
                            ClubId = 11,
                            ImageUrl = "/images/session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Live",
                            Schedules = "10h00",
                            Score = 4
                        },
                        new
                        {
                            Id = 32,
                            CapacityMax = 20,
                            ClubId = 11,
                            ImageUrl = "/images/session/GroupClasses.jpg",
                            IsComplete = false,
                            Name = "Cours Collectifs Virtuel",
                            Schedules = "15h00",
                            Score = 3
                        },
                        new
                        {
                            Id = 33,
                            CapacityMax = 2,
                            ClubId = 11,
                            ImageUrl = "/images/session/PersonalTrainer.jpeg",
                            IsComplete = false,
                            Name = "Entraineur Personnel",
                            Schedules = "18h00",
                            Score = 5
                        });
                });

            modelBuilder.Entity("RemSlyCore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassWord")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "7 rue de la Paix, 59000 Lille",
                            AvatarUrl = "/Images/Avatar/Christophe.jpg",
                            Email = "christophe@gmail.com",
                            FirstName = "Christophe",
                            Gender = 0,
                            IsAdmin = true,
                            LastName = "Chauveau",
                            PassWord = "christophe123",
                            PhoneNumber = "0607019001",
                            PostalCode = "59000"
                        },
                        new
                        {
                            Id = 2,
                            Address = "41 rue de Calais, 59130 Lambersart",
                            AvatarUrl = "/Images/Avatar/Anthony.jpg",
                            Email = "anthony@gmail.com",
                            FirstName = "Anthony",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Boisselet",
                            PassWord = "anthony123",
                            PhoneNumber = "0647911071",
                            PostalCode = "59130"
                        },
                        new
                        {
                            Id = 3,
                            Address = "33 rue des Fleurs, 59650 Villeneuve d'Ascq",
                            AvatarUrl = "/Images/Avatar/Thomas.jpg",
                            Email = "thomas@gmail.com",
                            FirstName = "Thomas",
                            Gender = 0,
                            IsAdmin = false,
                            LastName = "Lavaud",
                            PassWord = "thomas123",
                            PhoneNumber = "0741810974",
                            PostalCode = "59650"
                        },
                        new
                        {
                            Id = 4,
                            Address = "9 rue des plantes, 59200 Tourcoing",
                            AvatarUrl = "/Images/Trainer/LauraTrainer.png",
                            Email = "laura@gmail.com",
                            FirstName = "Laura",
                            Gender = 1,
                            IsAdmin = false,
                            LastName = "Delcroix",
                            PassWord = "laura123",
                            PhoneNumber = "0644810904",
                            PostalCode = "59200"
                        },
                        new
                        {
                            Id = 5,
                            Address = "14 avenue de Dunkerque, 59160 Lille",
                            AvatarUrl = "/Images/Trainer/AmelieTrainer.jpg",
                            Email = "amelie@gmail.com",
                            FirstName = "Amelie",
                            Gender = 1,
                            IsAdmin = false,
                            LastName = "Duchemin",
                            PassWord = "amelie123",
                            PhoneNumber = "0709749425",
                            PostalCode = "59160"
                        });
                });

            modelBuilder.Entity("ClubMaterial", b =>
                {
                    b.HasOne("RemSlyCore.Models.Club", null)
                        .WithMany()
                        .HasForeignKey("ClubsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RemSlyCore.Models.Material", null)
                        .WithMany()
                        .HasForeignKey("MaterialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RemSlyCore.Models.Club", b =>
                {
                    b.HasOne("RemSlyCore.Models.User", null)
                        .WithMany("Favorites_Clubs")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("RemSlyCore.Models.Commentary", b =>
                {
                    b.HasOne("RemSlyCore.Models.Session", "Session")
                        .WithMany("Comments")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RemSlyCore.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RemSlyCore.Models.Reservation", b =>
                {
                    b.HasOne("RemSlyCore.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RemSlyCore.Models.ReservationSession", b =>
                {
                    b.HasOne("RemSlyCore.Models.Reservation", "Reservation")
                        .WithMany("ReservationSessions")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RemSlyCore.Models.Session", "Session")
                        .WithMany("ReservationSessions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reservation");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RemSlyCore.Models.Session", b =>
                {
                    b.HasOne("RemSlyCore.Models.Club", "Club")
                        .WithMany("Sessions")
                        .HasForeignKey("ClubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RemSlyCore.Models.User", null)
                        .WithMany("Favorites_Sessions")
                        .HasForeignKey("UserId");

                    b.Navigation("Club");
                });

            modelBuilder.Entity("RemSlyCore.Models.Club", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("RemSlyCore.Models.Reservation", b =>
                {
                    b.Navigation("ReservationSessions");
                });

            modelBuilder.Entity("RemSlyCore.Models.Session", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ReservationSessions");
                });

            modelBuilder.Entity("RemSlyCore.Models.User", b =>
                {
                    b.Navigation("Favorites_Clubs");

                    b.Navigation("Favorites_Sessions");
                });
#pragma warning restore 612, 618
        }
    }
}
